# Generated by Django 5.0 on 2023-12-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=255)),
                ('Resume', models.TextField()),
                ('auteurs', models.CharField(max_length=255)),
                ('Institution', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('MotsCles', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('URL_Pdf', models.CharField(max_length=255)),
                ('RefBib', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomUtilisateur', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MotDePasse', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.articles')),
                ('UtilisateurID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
            options={
                'unique_together': {('UtilisateurID', 'ArticleID')},
            },
        ),
    ]
