# Generated by Django 4.1.7 on 2023-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_articles_pdf_file_alter_articles_motscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='auteurs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pdf_File',
            field=models.FileField(blank=True, null=True, upload_to='article_pdfs/'),
        ),
    ]
