# Generated by Django 4.1.7 on 2023-12-26 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_alter_articles_institution_alter_articles_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pdf_File',
            field=models.FileField(blank=True, null=True, upload_to='article_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
