# Generated by Django 4.1.7 on 2023-12-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_articles_id'),
        ('backendapp', '0004_alter_articles_pdf_file'),
    ]

    operations = [
    ]
