# Generated by Django 4.2 on 2023-12-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_articles_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='id',
            new_name='uuid',
        ),
    ]
