# Generated by Django 4.1.7 on 2023-12-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_merge_20231228_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
