# Generated by Django 4.2 on 2023-12-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_utilisateurs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='user',
        ),
    ]
