# Generated by Django 4.1.7 on 2024-01-02 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_alter_articles_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('URL_Pdf', models.URLField(blank=True, max_length=255, null=True)),
                ('pdf_File', models.FileField(blank=True, null=True, upload_to='article_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
