# Generated by Django 5.0 on 2023-12-31 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_alter_articles_id'),
        ('backendapp', '0011_utilisateurs_alter_favoris_utilisateurid_and_more'),
    ]

    operations = [
    ]
