# Generated by Django 5.0 on 2024-01-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_articlefile_alter_articles_id'),
        ('backendapp', '0012_merge_20231231_0344'),
    ]

    operations = [
    ]
