# Generated by Django 5.0 on 2024-01-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_merge_20240103_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together=set(),
        ),
    ]
