# Generated by Django 5.0 on 2024-01-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0014_alter_favoris_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together={('UtilisateurID', 'ArticleID')},
        ),
    ]
