version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    
frontend:
  build: ./client/frontend
  container_name: frontend_c
  depends_on:
    - django
  ports:
    - "3000:3000"
  stdin_open: true
  tty: true